name: CI
on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install texlive
        run: sudo apt install texlive-base texlive-xetex
      - name: Install texlive extra
        run: sudo apt-get install texlive-latex-extra texlive-fonts-extra  texlive-bibtex-extra biber
      - name: Build cv
        run: |
          pdflatex main.tex
          biber main
          pdflatex main.tex 
          pdflatex main.tex 
      - name: Build english cv
        run: |
          pdflatex main_en.tex
          biber main_en
          pdflatex main_en.tex 
          pdflatex main_en.tex 
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with: 
          commit-message: pdflatex build
          branch: pdflatex_build
          title: '[CI] pdflatex build'
