name: CI
on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install texlive
        run: sudo apt install texlive-base texlive-xetex
      - name: Install texlive extra
        run: sudo apt-get install texlive-latex-extra texlive-fonts-extra  texlive-bibtex-extra biber
      - name: Build cv
        run: xelatex main.tex -o output/cv.pdf
      - name: Build english cv
        run: xelatex main_en.tex -o output/cv_en.pdf
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with: 
          commit-message: xelatex build
          branch: xelatex_build
          title: '[CI] xelatex build'
